# Generated by Django 4.2.5 on 2023-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('cod_art', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
