# Generated by Django 4.2.5 on 2023-11-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_pedido_detalle_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'managed': False},
        ),
    ]
