# Generated by Django 4.2.5 on 2023-11-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_detalle_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'managed': True},
        ),
    ]
