# Generated by Django 4.2.5 on 2023-11-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_detalle_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'managed': False},
        ),
    ]
