# Generated by Django 4.2.5 on 2023-10-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('cod_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('cod_art', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('stock', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
