# Generated by Django 4.2.5 on 2023-10-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('cod_a', models.AutoField(primary_key=True, serialize=False)),
                ('cod_usuario', models.IntegerField()),
            ],
        ),
    ]
