# Generated by Django 4.2.5 on 2023-10-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
