# Generated by Django 4.2.5 on 2023-10-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id_detalle_ped', models.IntegerField(primary_key=True, serialize=False)),
                ('id_pedido', models.IntegerField()),
                ('cod_art', models.IntegerField()),
                ('cod_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
