# Generated by Django 4.2.5 on 2023-11-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_detalle_pedido_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle_pedido',
        ),
    ]
