# Generated by Django 4.2.5 on 2023-11-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_detallepedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
    ]
