# Generated by Django 4.2.5 on 2023-11-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_alter_detallepedido_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallepedido',
            table='detalle_pedidos',
        ),
    ]
