# Generated by Django 4.2.5 on 2023-11-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_detalle_pedido_delete_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('pedido', models.OneToOneField(db_column='pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pedido.pedido')),
                ('cant_pedida', models.IntegerField(db_column='cant_pedida')),
                ('cant_entregada', models.IntegerField(db_column='cant_entregada')),
            ],
            options={
                'db_table': 'detalle_pedidos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='detalle_pedido',
        ),
    ]
