# Generated by Django 4.2.5 on 2023-11-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_detalle_pedido_delete_detalle_pedidos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalle_pedido',
            table='detalle_pedido',
        ),
    ]
