# Generated by Django 4.2.5 on 2023-11-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_detalle_pedidos_pedidos_delete_detalle_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('nro_remito', models.AutoField(db_column='nro_remito', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='fecha', null=True)),
                ('fm_sol', models.CharField(blank=True, db_column='fm_sol', max_length=50, null=True)),
                ('c_total', models.IntegerField(blank=True, db_column='c_total', null=True)),
                ('fecha_pedido', models.DateField(blank=True, db_column='fecha_pedido', null=True)),
            ],
            options={
                'db_table': 'remito',
                'managed': False,
            },
        ),
    ]
